version: "3.7"
services:
  source_db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: james-bond
      POSTGRES_PASSWORD: james-bond123@7!'3aaR
      POSTGRES_DB: postgres-db
    command: >
      -c max_connections=200
      -c wal_level=logical
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    networks:
      localnet:

  target_db:
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: james-bond
      POSTGRES_PASSWORD: james-bond123@7!'3aaR
      POSTGRES_DB: postgres-db
    command: >
      -c max_connections=200
      -c wal_level=logical
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    networks:
      localnet:

networks:
  localnet:
